export type ReceiptExportData = {
  status: string;
  title: string;
  agreement: string;
  milestone: string;
  amount: string;
  recipient: string | null;
  network: string;
  date: string;
  txHash: string;
  approvalChecklist?: readonly string[];
};

export function receiptExportText(receipt: ReceiptExportData) {
  const checklist = receipt.approvalChecklist?.length
    ? `\nApproval checklist\n${receipt.approvalChecklist.map((item) => `- ${item}`).join("\n")}\n`
    : "";
  return [
    "DUEVIA SETTLEMENT RECEIPT",
    "==========================",
    `Status: ${receipt.status}`,
    `Agreement: ${receipt.agreement}`,
    `Milestone: ${receipt.milestone}`,
    `Amount: ${receipt.amount}`,
    `Recipient: ${receipt.recipient ?? "Recorded onchain"}`,
    `Network: ${receipt.network}`,
    `Date: ${receipt.date}`,
    `Arc transaction: ${receipt.txHash}`,
    checklist.trim(),
    "This record is generated by Duevia. Verify the transaction directly on ArcScan.",
  ].filter(Boolean).join("\n");
}

export function receiptExportFilename(receipt: Pick<ReceiptExportData, "agreement" | "milestone">) {
  const milestone = receipt.milestone.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase();
  return `duevia-${receipt.agreement.toLowerCase()}-${milestone || "receipt"}.txt`;
}
